### PR TITLE
added sorting and search algorithms

### PR DESCRIPTION
**Pull request by susmita2000**

### CODE REVIEW

**Comment by thepurpleowl** [comment]
@susmita2000 Make two new folders Sorting and Searching in Basics/ and your files in appropriate folders.

Also, update the README.

**Comment by susmita2000** [comment]
Yes I have made two separate folders for sorting and searching. Could you please merge my pr.

**Comment by thepurpleowl** [comment]
@susmita2000 Please update the README in Basics/ folder

**Comment by susmita2000** [comment]
Done! I had to create a separate pr for Readme.

**Comment by thepurpleowl** [comment]
@susmita2000 Please don't create another PR for such a small change. This is not in line with the spirits of good s/w management.

Please make that change as a part of this PR. I am closing the other PR.

**Review by thepurpleowl — APPROVED** [review]

**Comment by susmita2000** [comment]
I had actually forked the code before addition of the readme file in basic directory. So now I have added the readme file and it has a conflict which has to be resolved. Could you please look into it?

**Review by thepurpleowl — APPROVED** [review]

**Pull request merged**
