### PR TITLE
Added square_root.cpp

### PR DESCRIPTION
**Pull request by ShehzadAhm**
Compute the square root of a number without inbuilt sqrt() function.

### CODE REVIEW

**Review by thepurpleowl — COMMENTED** [review]
@ShehzadAhm This is not a binary search problem. You can add it in some platform spefic folder and update the README of that specific folder.

**Comment by ShehzadAhm** [comment]
@thepurpleowl It uses binary search algorithm

**Comment by thepurpleowl** [comment]
@ShehzadAhm only standard algos should be inside Basics/. For others you need to add to appropriate subdirectory with updated README.

**Comment by ShehzadAhm** [comment]
@thepurpleowl Ok I will create a new directory.

**Pull request closed without merging**
