### PR TITLE
added solution for exercise #278 on Leetcode

### PR DESCRIPTION
**Pull request by melkilic**

### CODE REVIEW

**Comment by thepurpleowl** [comment]
@melkilic Please create another folder for Leetcode in parent dir and add you code with a README.md for Leetcode folder

**Comment by melkilic** [comment]
I changed it, as you said. Could you check to see whether it’s correct?

**Comment by thepurpleowl** [comment]
@melkilic if this is a LeetCode problem, add it in Leetcode folder and update the README of Leetcode. You are adding in Basics/

**Comment by thepurpleowl** [comment]
You raised another PR. Closing this.

**Pull request closed without merging**
