### PR TITLE
Added Leetcode folder with a Java Solution

### PR DESCRIPTION
**Pull request by SandeepGamot**
Added a LeetCode folder with language specific subfolders to bring some organizations in the repo.
Added a java solution to Medium Problem. More to come.

### CODE REVIEW

**Comment by thepurpleowl** [comment]
Please add a README in Leetcode folder @SandeepGamot 

And change the path from 
`LeetCode/Java/Longest_Substring_Without_Repeating_Characters.java` to 
`LeetCode/Longest_Substring_Without_Repeating_Characters.java`

**Comment by SandeepGamot** [comment]
Hey, @thepurpleowl it's done now.

**Review by thepurpleowl — COMMENTED** [review]
@SandeepGamot Binary search folder is already added. Can you add you binary search files into existing Basics/Binary_Search.

**Comment by SandeepGamot** [comment]
Oh yeah, I got out of sync with the master, no worries I'll add them there.
Hey, @thepurpleowl I'll suggest to delete this PR, I'll make a fresh new one.

**Pull request closed without merging**
